version: "3"

volumes:
  eudico-data: {}
  grafana: {}

services:
  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/90d8kOfU*^cR

  neodash:
    image: nielsdejong/neodash:latest
    ports:
      - 5005:5005

  all-in-one:
    image: eudico:latest
    environment:
      EUDICO_STATS_NEO4J_URI: neo4j://neo4j:7687
      EUDICO_STATS_NEO4J_USERNAME: neo4j
      EUDICO_STATS_NEO4J_PASSWORD: 90d8kOfU*^cR
    volumes:
      - eudico-data:/home/eudico/.eudico
      - ./scripts/eudico-stats.sh:/home/eudico/eudico-stats.sh
      - ./credentials:/home/eudico/credentials
    ports:
      - 1234:1234
      - 6689:6689
      - 6688:6688
      - 2345:2345
    command:
      - -a  # start "all in one"

  # prometheus:
  #   image: prom/prometheus
  #   volumes:
  #     - ./cmd/eudico-stats/prometheus.yml:/etc/prometheus/prometheus.yml
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.console.libraries=/usr/share/prometheus/console_libraries'
  #     - '--web.console.templates=/usr/share/prometheus/consoles'
  #   ports:
  #     - 9090:9090

  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "13000:3000"
  #   depends_on:
  #     - prometheus
  #   volumes:
  #     - grafana:/var/lib/grafana